services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - .env

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - elerna-app

  elerna-api-service:
    container_name: elerna-service
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - elerna-app
    volumes:
      - E:\Exercise\Elerna\src\main\resources\Lesson:/app/lesson_folder
      - E:\Exercise\Elerna\src\main\resources\Assignment:/app/assignment_folder
      - E:\Exercise\Elerna\src\main\resources\Contest:/app/contest_folder
      - E:\Exercise\Elerna\src\main\resources\Submission:/app/submission_folder

volumes:
  db_data:

networks:
  elerna-app:
    driver: bridge
