spring:
  config:
    active:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:elerna}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:@Ttg123456}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      hibernate:
        ddl-auto: none


#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
openapi:
  info:
    title: Elerna API Services
    description: This is Elerna, an E-Learning Backend Application
    version: 1.0.0
  server:
    url: http://localhost:${APP_PORT:80}
    description: Elerna Dev Server
  service:
    server: http://localhost:${server.port}
    v1:
      api-docs: api-service-v1
      package: com.application.elerna.controller.v1
    title: API Document
    version: 1.0.0

jwt:
  expirationHour: 1
  expirationDay: 14
  secretKey: f23f5983b54d69ff22c22661ff764de82beef64ec25137be5be1acbfb98bcf8a
  refreshKey: f526795c95399cea27c055c842c3d6ab018ed0fa4f66f701c28ab22dec28237b
  resetKey: 7c18b43a1d8227cddb332e67971e790ce35ac2303f4fccfb2a565622f2fe1cec

course:
  lessonFolder: ${LESSON_FOLDER:E:\Exercise\Elerna\src\main\resources\Lesson}
  assignmentFolder: ${ASSIGN_FOLDER:E:\Exercise\Elerna\src\main\resources\Assignment}
  contestFolder: ${CONTEST_FOLDER:E:\Exercise\Elerna\src\main\resources\Contest}
  submissionFolder: ${SUBMISSION_FOLDER:E:\Exercise\Elerna\src\main\resources\Submission}