package com.application.elerna.utils;

import org.springframework.stereotype.Component;

@Component
public class EndpointDescription {

    public static final String signupDescription = "User signs up. User sends a request with register information and then receive access and refresh token to verify request";

    public static final String loginDescription = "User logins. They send username and password to server. Server authenticates this username with database, and provide access and refresh token if they are valid";

    public static final String logoutDescription = "User logs out. User logs out from application and their token is set to inactive. So, if they want to access the application, they must login and get new access token";

    public static final String confirmResetDescription = "Admin sends confirm reset request. After users send email to raise reset password request, admin sends a confirmation back to them. It includes reset token generated by username.";

    public static final String forgotPasswordDescription = "Users send forgot password request. Users send a request with their email to start reset password.";

    public static final String refreshTokenDescription = "Admin refreshes. Admid uses refresh token to get username, password and generates new access token.";

    public static final String resetPasswordDescription = "Admin and user resets password. User input password and confirm password, and then admin will update to database.";

    public static final String sendEmailDescription = "Admin sends email. After verifying email sent by user, admin sends a confirmation email to user and get reset token back for the second verification.";

    public static final String payDescription = "User pays for course. First, admin checks whether user's bank account has enough credit for payment request or not, and then take place paying for this request. After that, new transaction was created and saved to database.";

    public static final String depositDescription = "User deposits money to his acocunt. User inputs amount and deposits to his bank account.";

    public static final String getAllTransactionDescription = "Admin gets all transaction list.";

    public static final String getTransactionHistory = "User gets transaction's history. Server gets username via authentication from access token, and then get his all transaction history.";

    public static final String getTransactionDetail = "User or admin gets transaction's details";

    public static final String getBankAccountLogs = "User gets his bank account's logs related to his account.";

    public static final String outTeamDescription = "User gets out of the team";

    public static final String joinTeamDescription = "User joins the team";

    public static final String createTeamDescription = "User creates team";

    public static final String getMemberListDescription = "User or admin gets all team's member list";

    public static final String getTeamListBySearchingDescription = "Admin gets all team list by searching";

    public static final String getJoinedTeamDescription = "User gets all joined teams";

    public static final String getTeamDetailDescription = "User or admin gets team's details";

    public static final String deleteTeamDescription = "User or admin deletes team";

    public static final String updateUserDetailDescription = "User or admin updates their details";

    public static final String getUserRole = "User or admin gets roles";

    public static final String getUserListBySorting = "Admin gets a list of users by some sorting criteria";

    public static final String getUserListBySearching = "Admin gets a list of users by some searching criteria";

    public static final String getUserDetail = "User or admin gets their details";

    public static final String deleteUser = "User or admin deletes their account";

    public static final String getAllCreatingRequestDescription = "Admin gets all creating course requests";

    public static final String sendCreatingRequestDescription = "User sends creating course request";

    public static final String approveCreatingRequest = "Admin approves creating course requests";

    public static final String rejectCreatingRequest = "Admin rejects creating course requests";

    public static final String confirmSignup = "Admin confirm for signing up new account";

}
